### ISSUE TITLE
_document is not found

### ISSUE THREAD

**Issue by ScriptedAlchemy** [martpie/next-transpile-modules#111]
- [x] I HAVE READ [THE FAQ](https://github.com/martpie/next-transpile-modules#faq) AND MY PROBLEM WAS NOT DESCRIBED THERE
- [x] I WILL GIVE 10$ TO CHARITY IF MY SOLUTION WAS ACTUALLY IN THE FAQ

**Are you trying to transpile a local package or an npm package?**
If an npm package, which one?
Local packages + some private ones

**Describe the bug**
A clear and concise description of what the bug is (don't forget the logs if applicable).

Using webpack 5, and transpile-modules 4.1 - I get a `_document.js` chunk not found error. 

**To Reproduce**
Steps to reproduce the behavior (a reproduction is even better):
This is a larger app, but everything worked with 4.0.1, all I did was upgrade to 4.1
Using NExt 9.5.2 and Webpack 5 beta 23

**Expected behavior**

**Setup**

- Next.js version: 9.5.2
- `next-transpile-modules` version: 4.1.0
- Node.js version: 12.13
- `npm`/`yarn` version: 1.16
- Operating System: OSX
- Webpack 4 or 5: 5

**Additional context**
here the error log
```
_document.js chunk not found
error - request.startsWith is not a function
Error: Cannot find module '/Users/zjackson/wae-coco/packages/site/.next/server/pages-manifest.json'
Require stack:
- /Users/zjackson/wae-coco/node_modules/next/dist/next-server/server/require.js
- /Users/zjackson/wae-coco/node_modules/next/dist/next-server/server/load-components.js
- /Users/zjackson/wae-coco/node_modules/next/dist/next-server/server/api-utils.js
- /Users/zjackson/wae-coco/node_modules/next/dist/next-server/server/next-server.js
- /Users/zjackson/wae-coco/node_modules/next/dist/server/next.js
- /Users/zjackson/wae-coco/packages/site/server/dev-server.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:797:15)
    at Function.Module._load (internal/modules/cjs/loader.js:690:27)
    at Module.require (internal/modules/cjs/loader.js:852:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at getPagePath (/Users/zjackson/wae-coco/node_modules/next/dist/next-server/server/require.js:1:657)
    at requirePage (/Users/zjackson/wae-coco/node_modules/next/dist/next-server/server/require.js:2:227)
    at loadComponents (/Users/zjackson/wae-coco/node_modules/next/dist/next-server/server/load-components.js:1:628)
    at DevServer.findPageComponents (/Users/zjackson/wae-coco/node_modules/next/dist/next-server/server/next-server.js:57:189)
    at DevServer.renderToHTML (/Users/zjackson/wae-coco/node_modules/next/dist/next-server/server/next-server.js:98:198)
    at DevServer.renderToHTML (/Users/zjackson/wae-coco/node_modules/next/dist/server/next-dev-server.js:30:590) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/Users/zjackson/wae-coco/node_modules/next/dist/next-server/server/require.js',
    '/Users/zjackson/wae-coco/node_modules/next/dist/next-server/server/load-components.js',
    '/Users/zjackson/wae-coco/node_modules/next/dist/next-server/server/api-utils.js',
    '/Users/zjackson/wae-coco/node_modules/next/dist/next-server/server/next-server.js',
    '/Users/zjackson/wae-coco/node_modules/next/dist/server/next.js',
    '/Users/zjackson/wae-coco/packages/site/server/dev-server.js'
  ]
}
```

**Comment by martpie** [comment]
Try removing the lock file, remove node_modules delete `.next/` and re-install dependencies, it usually does the trick.

**Comment by ScriptedAlchemy** [comment]
Appreciate it!
